class TrainingPipelineConfig:
    




class DataIngestionConfig:...
class DataTransformationConfig:...
class DataValidationConfig:...
class ModelTrainerConfig:...
class ModelEvaluateConfig:...
class ModelPusherConfig:...